#! /bin/bash

# echo "what is the filename?"
# read -p "What is the filename?: " FILENAME
# FILENAME=$1 $2 $3 $4 $5
for FILENAME in $@
do
    sleep 1

    if [ -s $FILENAME ]
    then 
        echo "sorry $FILENAME already exists.."
    else
        echo "creating $FILENAME ..."
        touch $FILENAME

        sleep 1
        echo "making ${FILENAME} executable... "
        chmod 755 $FILENAME 

        sleep 1
        echo "declaring SHEBANG into $FILENAME..."
        echo "#!/bin/bash" > $FILENAME

    fi

done